// generated by unplugin-svelte-components
// We suggest you to commit this file into source control
declare global {
  const Button: typeof import('./src/components/atoms/Button.svelte')['default'];
  const Modal: typeof import('./src/components/organisms/Modal.svelte')['default'];
}

export {};
