#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building Primir before committing'

yarn format

# Check Prettier standards
yarn check-format ||
(
    echo '🤢🤮🤢🤮 Prettier Check Failed. Run yarn format, add changes and try commit again. 🤢🤮🤢🤮';
    false;
)

# Check ESLint Standards
yarn check-lint ||
(
    echo '😤🏀👋😤 ESLint Check Failed. Make the required changes listed above, add changes and try to commit again. 😤🏀👋😤'
    false; 
)

# Check tsconfig standards
yarn check-types ||
(
    echo '🤡😂❌🤡 Failed Type check. Make the changes required above. 🤡😂❌🤡'
    false;
)

echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
